-- Update/Insert script for batch job parameters
-- This script will UPDATE existing parameters and INSERT missing ones
-- Updates all batch job flags for specified batch jobs
--
-- Jobs with original values (force_grid_size=50, force_chunk=100):
--   loanAccountDpdCalcJob, loanAccountAssetCriteriaJob, loanAccountAssetClassificationJob,
--   penalInterestAccrualCalculation, penalInterestAccrualBooking, loanAccountClosure,
--   interestAccrualCalculation, interestAccrualPosting, loanAccountBillingJob,
--   updateLoanAccountDerivedFieldsJob
--
-- Jobs with new values (force_grid_size=24, force_chunk=20):
--   accountingBankServiceRetryJob, triggerRejectConductBetTask, collectNowFinalFlowSubmission,
--   collectNowGenerateReceiptNotificationJob, collectNowGenerateReceiptNotificationCHJob,
--   collectNowGenerateReceiptNotificationRMJob, primaryAllocateCollection,
--   secondaryAllocateCollection, expirePastCollections, createTaskForNewMfiCollections,
--   updateExpiredScheduledBatchStatus, calculateUserTatBatch,
--   cashDepositCutoffTimeElapsedForCollectorJob, createTaskBatch, triggerRejectGroupBetTask,
--   collToStagNpHandOffFileSyncJob, triggerRejectIndividualBetTask,
--   childLoanEventProcessingBatchJob, loanRecurringPaymentBatchApi, deleteAccountingTaskUsingCode,
--   loanAdvanceRepayment, deathForeclosureInsuranceJob, bulkSGToDisbursementCancellationJob,
--   bulkSGToPostDisbursementInsuranceUpdateJob, updateLoanAccountDerivedFieldsMonthlyJob,
--   generateNocFileJob, proactiveExcessAmountRefund, proactiveExcessAmountRefundStaging,
--   proactiveReverseTransaction, generateTBZeroisationReport, trialBalanceZeroisationJob,
--   triggerNetOffMarking, loanInstallmentBounceNotificationJob, loanInstallmentDueNotificationJob,
--   apyRegistration, triggerCkycApiCallBatch, generateCustomerLevelDataExtractJob,
--   triggerDisburseLoan, triggerDocumentDispatchTask, ftsAccountOpeningFormBatch,
--   triggerUploadDocument, runNeftTransactionUploadJob, notifyUsersForPendingTasksJob,
--   generatePerformanceSummaryJob, rejectExpiredGroupCasaTask, triggerRejectPdcTask,
--   reminderForPtpCalenderCustomerJob, reminderForPtpCalenderUserJob,
--   reminderForPtpCalenderUserJobRm, assetBaseFileSyncJob, generateEnachRepresentationFile,
--   processingSIReverseFeedFiles, retrySIJob, supervisorDashboardLoanCategoryTaggingJob,
--   supervisorDashboardSkippedPTPTaggingJob, supervisorReviewTaskJob,
--   collToStagNpTrialHistorySyncJob, generateTrendAndReviewDashboardJob, triggerNotifications
--
-- Flags being set:
--   For original jobs: force_chunk='100', force_grid_size='50'
--   For new jobs: force_chunk='20', force_grid_size='24'
--   For all jobs: force_async='TRUE', is_multi_node='TRUE', force_consumer_async='FALSE',
--                 force_ex_channel='FALSE', force_task_executor='FALSE', force_msg_driven='TRUE'

-- ============================================================================
-- SECTION 1: UPDATE STATEMENTS
-- ============================================================================

-- UPDATE force_chunk for original jobs (value: '100')
UPDATE batch_job_parameter 
SET param_value = '100' 
WHERE param_name = 'force_chunk' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'loanaccountdpdcalcjob',
      'loanaccountassetcriteriasjob',
      'loanaccountassetclassificationjob',
      'penalinterestaccrualcalculation',
      'penalinterestaccrualbooking',
      'loanaccountclosure',
      'interestaccrualcalculation',
      'interestaccrualposting',
      'loanaccountbillingjob',
      'updateloanaccountderivedfieldsjob'
    )
  );

-- UPDATE force_chunk for new jobs (value: '20')
UPDATE batch_job_parameter 
SET param_value = '20' 
WHERE param_name = 'force_chunk' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'accountingbankserviceretryjob',
      'triggerrejectconductbettask',
      'collectnowfinalflowsubmission',
      'collectnowgeneratereceiptnotificationjob',
      'collectnowgeneratereceiptnotificationchjob',
      'collectnowgeneratereceiptnotificationrmjob',
      'primaryallocatecollection',
      'secondaryallocatecollection',
      'expirepastcollections',
      'createtaskfornewmficollections',
      'updateexpiredscheduledbatchstatus',
      'calculateusertatbatch',
      'cashdepositcutofftimeelapsedforcollectorjob',
      'createtaskbatch',
      'triggerrejectgroupbettask',
      'colltostagnphandofffilesyncjob',
      'triggerrejectindividualbettask',
      'childloaneventprocessingbatchjob',
      'loanrecurringpaymentbatchapi',
      'deleteaccountingtaskusingcode',
      'loanadvancerepayment',
      'deathforeclosureinsurancejob',
      'bulksgtodisbursementcancellationjob',
      'bulksgtopostdisbursementinsuranceupdatejob',
      'updateloanaccountderivedfieldsmonthlyjob',
      'generatenocfilejob',
      'proactiveexcessamountrefund',
      'proactiveexcessamountrefundstaging',
      'proactivereversetransaction',
      'generatetbzeroisationreport',
      'trialbalancezeroisationjob',
      'triggernetoffmarking',
      'loaninstallmentbouncenotificationjob',
      'loaninstallmentduenotificationjob',
      'apyregistration',
      'triggerckycapicallbatch',
      'generatecustomerleveldataextractjob',
      'triggerdisburseloan',
      'triggerdocumentdispatchtask',
      'ftsaccountopeningformbatch',
      'triggeruploaddocument',
      'runnefttransactionuploadjob',
      'notifyusersforpendingtasksjob',
      'generateperformancesummaryjob',
      'rejectexpiredgroupcasatask',
      'triggerrejectpdctask',
      'reminderforptpcalendercustomerjob',
      'reminderforptpcalenderuserjob',
      'reminderforptpcalenderuserjobrm',
      'assetbasefilesyncjob',
      'generateenachrepresentationfile',
      'processingsireversefeedfiles',
      'retrysijob',
      'supervisordashboardloancategorytaggingjob',
      'supervisordashboardskippedptptaggingjob',
      'supervisorreviewtaskjob',
      'colltostagnptrialhistorysyncjob',
      'generatetrendandreviewdashboardjob',
      'triggernotifications'
    )
  );

-- UPDATE force_grid_size for original jobs (value: '50')
UPDATE batch_job_parameter 
SET param_value = '50' 
WHERE param_name = 'force_grid_size' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'loanaccountdpdcalcjob',
      'loanaccountassetcriteriasjob',
      'loanaccountassetclassificationjob',
      'penalinterestaccrualcalculation',
      'penalinterestaccrualbooking',
      'loanaccountclosure',
      'interestaccrualcalculation',
      'interestaccrualposting',
      'loanaccountbillingjob',
      'updateloanaccountderivedfieldsjob'
    )
  );

-- UPDATE force_grid_size for new jobs (value: '24')
UPDATE batch_job_parameter 
SET param_value = '24' 
WHERE param_name = 'force_grid_size' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'accountingbankserviceretryjob',
      'triggerrejectconductbettask',
      'collectnowfinalflowsubmission',
      'collectnowgeneratereceiptnotificationjob',
      'collectnowgeneratereceiptnotificationchjob',
      'collectnowgeneratereceiptnotificationrmjob',
      'primaryallocatecollection',
      'secondaryallocatecollection',
      'expirepastcollections',
      'createtaskfornewmficollections',
      'updateexpiredscheduledbatchstatus',
      'calculateusertatbatch',
      'cashdepositcutofftimeelapsedforcollectorjob',
      'createtaskbatch',
      'triggerrejectgroupbettask',
      'colltostagnphandofffilesyncjob',
      'triggerrejectindividualbettask',
      'childloaneventprocessingbatchjob',
      'loanrecurringpaymentbatchapi',
      'deleteaccountingtaskusingcode',
      'loanadvancerepayment',
      'deathforeclosureinsurancejob',
      'bulksgtodisbursementcancellationjob',
      'bulksgtopostdisbursementinsuranceupdatejob',
      'updateloanaccountderivedfieldsmonthlyjob',
      'generatenocfilejob',
      'proactiveexcessamountrefund',
      'proactiveexcessamountrefundstaging',
      'proactivereversetransaction',
      'generatetbzeroisationreport',
      'trialbalancezeroisationjob',
      'triggernetoffmarking',
      'loaninstallmentbouncenotificationjob',
      'loaninstallmentduenotificationjob',
      'apyregistration',
      'triggerckycapicallbatch',
      'generatecustomerleveldataextractjob',
      'triggerdisburseloan',
      'triggerdocumentdispatchtask',
      'ftsaccountopeningformbatch',
      'triggeruploaddocument',
      'runnefttransactionuploadjob',
      'notifyusersforpendingtasksjob',
      'generateperformancesummaryjob',
      'rejectexpiredgroupcasatask',
      'triggerrejectpdctask',
      'reminderforptpcalendercustomerjob',
      'reminderforptpcalenderuserjob',
      'reminderforptpcalenderuserjobrm',
      'assetbasefilesyncjob',
      'generateenachrepresentationfile',
      'processingsireversefeedfiles',
      'retrysijob',
      'supervisordashboardloancategorytaggingjob',
      'supervisordashboardskippedptptaggingjob',
      'supervisorreviewtaskjob',
      'colltostagnptrialhistorysyncjob',
      'generatetrendandreviewdashboardjob',
      'triggernotifications'
    )
  );

-- UPDATE force_async = 'TRUE' for all jobs
UPDATE batch_job_parameter 
SET param_value = 'TRUE' 
WHERE param_name = 'force_async' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'loanaccountdpdcalcjob',
      'loanaccountassetcriteriasjob',
      'loanaccountassetclassificationjob',
      'penalinterestaccrualcalculation',
      'penalinterestaccrualbooking',
      'loanaccountclosure',
      'interestaccrualcalculation',
      'interestaccrualposting',
      'loanaccountbillingjob',
      'updateloanaccountderivedfieldsjob',
      'accountingbankserviceretryjob',
      'triggerrejectconductbettask',
      'collectnowfinalflowsubmission',
      'collectnowgeneratereceiptnotificationjob',
      'collectnowgeneratereceiptnotificationchjob',
      'collectnowgeneratereceiptnotificationrmjob',
      'primaryallocatecollection',
      'secondaryallocatecollection',
      'expirepastcollections',
      'createtaskfornewmficollections',
      'updateexpiredscheduledbatchstatus',
      'calculateusertatbatch',
      'cashdepositcutofftimeelapsedforcollectorjob',
      'createtaskbatch',
      'triggerrejectgroupbettask',
      'colltostagnphandofffilesyncjob',
      'triggerrejectindividualbettask',
      'childloaneventprocessingbatchjob',
      'loanrecurringpaymentbatchapi',
      'deleteaccountingtaskusingcode',
      'loanadvancerepayment',
      'deathforeclosureinsurancejob',
      'bulksgtodisbursementcancellationjob',
      'bulksgtopostdisbursementinsuranceupdatejob',
      'updateloanaccountderivedfieldsmonthlyjob',
      'generatenocfilejob',
      'proactiveexcessamountrefund',
      'proactiveexcessamountrefundstaging',
      'proactivereversetransaction',
      'generatetbzeroisationreport',
      'trialbalancezeroisationjob',
      'triggernetoffmarking',
      'loaninstallmentbouncenotificationjob',
      'loaninstallmentduenotificationjob',
      'apyregistration',
      'triggerckycapicallbatch',
      'generatecustomerleveldataextractjob',
      'triggerdisburseloan',
      'triggerdocumentdispatchtask',
      'ftsaccountopeningformbatch',
      'triggeruploaddocument',
      'runnefttransactionuploadjob',
      'notifyusersforpendingtasksjob',
      'generateperformancesummaryjob',
      'rejectexpiredgroupcasatask',
      'triggerrejectpdctask',
      'reminderforptpcalendercustomerjob',
      'reminderforptpcalenderuserjob',
      'reminderforptpcalenderuserjobrm',
      'assetbasefilesyncjob',
      'generateenachrepresentationfile',
      'processingsireversefeedfiles',
      'retrysijob',
      'supervisordashboardloancategorytaggingjob',
      'supervisordashboardskippedptptaggingjob',
      'supervisorreviewtaskjob',
      'colltostagnptrialhistorysyncjob',
      'generatetrendandreviewdashboardjob',
      'triggernotifications'
    )
  );

-- UPDATE is_multi_node = 'TRUE' for all jobs
UPDATE batch_job_parameter 
SET param_value = 'TRUE' 
WHERE param_name = 'is_multi_node' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'loanaccountdpdcalcjob',
      'loanaccountassetcriteriasjob',
      'loanaccountassetclassificationjob',
      'penalinterestaccrualcalculation',
      'penalinterestaccrualbooking',
      'loanaccountclosure',
      'interestaccrualcalculation',
      'interestaccrualposting',
      'loanaccountbillingjob',
      'updateloanaccountderivedfieldsjob',
      'accountingbankserviceretryjob',
      'triggerrejectconductbettask',
      'collectnowfinalflowsubmission',
      'collectnowgeneratereceiptnotificationjob',
      'collectnowgeneratereceiptnotificationchjob',
      'collectnowgeneratereceiptnotificationrmjob',
      'primaryallocatecollection',
      'secondaryallocatecollection',
      'expirepastcollections',
      'createtaskfornewmficollections',
      'updateexpiredscheduledbatchstatus',
      'calculateusertatbatch',
      'cashdepositcutofftimeelapsedforcollectorjob',
      'createtaskbatch',
      'triggerrejectgroupbettask',
      'colltostagnphandofffilesyncjob',
      'triggerrejectindividualbettask',
      'childloaneventprocessingbatchjob',
      'loanrecurringpaymentbatchapi',
      'deleteaccountingtaskusingcode',
      'loanadvancerepayment',
      'deathforeclosureinsurancejob',
      'bulksgtodisbursementcancellationjob',
      'bulksgtopostdisbursementinsuranceupdatejob',
      'updateloanaccountderivedfieldsmonthlyjob',
      'generatenocfilejob',
      'proactiveexcessamountrefund',
      'proactiveexcessamountrefundstaging',
      'proactivereversetransaction',
      'generatetbzeroisationreport',
      'trialbalancezeroisationjob',
      'triggernetoffmarking',
      'loaninstallmentbouncenotificationjob',
      'loaninstallmentduenotificationjob',
      'apyregistration',
      'triggerckycapicallbatch',
      'generatecustomerleveldataextractjob',
      'triggerdisburseloan',
      'triggerdocumentdispatchtask',
      'ftsaccountopeningformbatch',
      'triggeruploaddocument',
      'runnefttransactionuploadjob',
      'notifyusersforpendingtasksjob',
      'generateperformancesummaryjob',
      'rejectexpiredgroupcasatask',
      'triggerrejectpdctask',
      'reminderforptpcalendercustomerjob',
      'reminderforptpcalenderuserjob',
      'reminderforptpcalenderuserjobrm',
      'assetbasefilesyncjob',
      'generateenachrepresentationfile',
      'processingsireversefeedfiles',
      'retrysijob',
      'supervisordashboardloancategorytaggingjob',
      'supervisordashboardskippedptptaggingjob',
      'supervisorreviewtaskjob',
      'colltostagnptrialhistorysyncjob',
      'generatetrendandreviewdashboardjob',
      'triggernotifications'
    )
  );

-- UPDATE force_consumer_async = 'FALSE' for all jobs
-- NOTE: Using force_msg_driven instead (better for high-throughput scenarios)
UPDATE batch_job_parameter 
SET param_value = 'FALSE' 
WHERE param_name = 'force_consumer_async' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'loanaccountdpdcalcjob',
      'loanaccountassetcriteriasjob',
      'loanaccountassetclassificationjob',
      'penalinterestaccrualcalculation',
      'penalinterestaccrualbooking',
      'loanaccountclosure',
      'interestaccrualcalculation',
      'interestaccrualposting',
      'loanaccountbillingjob',
      'updateloanaccountderivedfieldsjob',
      'accountingbankserviceretryjob',
      'triggerrejectconductbettask',
      'collectnowfinalflowsubmission',
      'collectnowgeneratereceiptnotificationjob',
      'collectnowgeneratereceiptnotificationchjob',
      'collectnowgeneratereceiptnotificationrmjob',
      'primaryallocatecollection',
      'secondaryallocatecollection',
      'expirepastcollections',
      'createtaskfornewmficollections',
      'updateexpiredscheduledbatchstatus',
      'calculateusertatbatch',
      'cashdepositcutofftimeelapsedforcollectorjob',
      'createtaskbatch',
      'triggerrejectgroupbettask',
      'colltostagnphandofffilesyncjob',
      'triggerrejectindividualbettask',
      'childloaneventprocessingbatchjob',
      'loanrecurringpaymentbatchapi',
      'deleteaccountingtaskusingcode',
      'loanadvancerepayment',
      'deathforeclosureinsurancejob',
      'bulksgtodisbursementcancellationjob',
      'bulksgtopostdisbursementinsuranceupdatejob',
      'updateloanaccountderivedfieldsmonthlyjob',
      'generatenocfilejob',
      'proactiveexcessamountrefund',
      'proactiveexcessamountrefundstaging',
      'proactivereversetransaction',
      'generatetbzeroisationreport',
      'trialbalancezeroisationjob',
      'triggernetoffmarking',
      'loaninstallmentbouncenotificationjob',
      'loaninstallmentduenotificationjob',
      'apyregistration',
      'triggerckycapicallbatch',
      'generatecustomerleveldataextractjob',
      'triggerdisburseloan',
      'triggerdocumentdispatchtask',
      'ftsaccountopeningformbatch',
      'triggeruploaddocument',
      'runnefttransactionuploadjob',
      'notifyusersforpendingtasksjob',
      'generateperformancesummaryjob',
      'rejectexpiredgroupcasatask',
      'triggerrejectpdctask',
      'reminderforptpcalendercustomerjob',
      'reminderforptpcalenderuserjob',
      'reminderforptpcalenderuserjobrm',
      'assetbasefilesyncjob',
      'generateenachrepresentationfile',
      'processingsireversefeedfiles',
      'retrysijob',
      'supervisordashboardloancategorytaggingjob',
      'supervisordashboardskippedptptaggingjob',
      'supervisorreviewtaskjob',
      'colltostagnptrialhistorysyncjob',
      'generatetrendandreviewdashboardjob',
      'triggernotifications'
    )
  );

-- UPDATE force_ex_channel = 'FALSE' for all jobs
-- NOTE: Set to 'TRUE' only if DB connection pool is large enough (100+ connections)
UPDATE batch_job_parameter 
SET param_value = 'FALSE' 
WHERE param_name = 'force_ex_channel' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'loanaccountdpdcalcjob',
      'loanaccountassetcriteriasjob',
      'loanaccountassetclassificationjob',
      'penalinterestaccrualcalculation',
      'penalinterestaccrualbooking',
      'loanaccountclosure',
      'interestaccrualcalculation',
      'interestaccrualposting',
      'loanaccountbillingjob',
      'updateloanaccountderivedfieldsjob',
      'accountingbankserviceretryjob',
      'triggerrejectconductbettask',
      'collectnowfinalflowsubmission',
      'collectnowgeneratereceiptnotificationjob',
      'collectnowgeneratereceiptnotificationchjob',
      'collectnowgeneratereceiptnotificationrmjob',
      'primaryallocatecollection',
      'secondaryallocatecollection',
      'expirepastcollections',
      'createtaskfornewmficollections',
      'updateexpiredscheduledbatchstatus',
      'calculateusertatbatch',
      'cashdepositcutofftimeelapsedforcollectorjob',
      'createtaskbatch',
      'triggerrejectgroupbettask',
      'colltostagnphandofffilesyncjob',
      'triggerrejectindividualbettask',
      'childloaneventprocessingbatchjob',
      'loanrecurringpaymentbatchapi',
      'deleteaccountingtaskusingcode',
      'loanadvancerepayment',
      'deathforeclosureinsurancejob',
      'bulksgtodisbursementcancellationjob',
      'bulksgtopostdisbursementinsuranceupdatejob',
      'updateloanaccountderivedfieldsmonthlyjob',
      'generatenocfilejob',
      'proactiveexcessamountrefund',
      'proactiveexcessamountrefundstaging',
      'proactivereversetransaction',
      'generatetbzeroisationreport',
      'trialbalancezeroisationjob',
      'triggernetoffmarking',
      'loaninstallmentbouncenotificationjob',
      'loaninstallmentduenotificationjob',
      'apyregistration',
      'triggerckycapicallbatch',
      'generatecustomerleveldataextractjob',
      'triggerdisburseloan',
      'triggerdocumentdispatchtask',
      'ftsaccountopeningformbatch',
      'triggeruploaddocument',
      'runnefttransactionuploadjob',
      'notifyusersforpendingtasksjob',
      'generateperformancesummaryjob',
      'rejectexpiredgroupcasatask',
      'triggerrejectpdctask',
      'reminderforptpcalendercustomerjob',
      'reminderforptpcalenderuserjob',
      'reminderforptpcalenderuserjobrm',
      'assetbasefilesyncjob',
      'generateenachrepresentationfile',
      'processingsireversefeedfiles',
      'retrysijob',
      'supervisordashboardloancategorytaggingjob',
      'supervisordashboardskippedptptaggingjob',
      'supervisorreviewtaskjob',
      'colltostagnptrialhistorysyncjob',
      'generatetrendandreviewdashboardjob',
      'triggernotifications'
    )
  );

-- UPDATE force_task_executor = 'FALSE' for all jobs
-- NOTE: Set to 'TRUE' only if DB connection pool is very large (200+ connections)
UPDATE batch_job_parameter 
SET param_value = 'FALSE' 
WHERE param_name = 'force_task_executor' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'loanaccountdpdcalcjob',
      'loanaccountassetcriteriasjob',
      'loanaccountassetclassificationjob',
      'penalinterestaccrualcalculation',
      'penalinterestaccrualbooking',
      'loanaccountclosure',
      'interestaccrualcalculation',
      'interestaccrualposting',
      'loanaccountbillingjob',
      'updateloanaccountderivedfieldsjob',
      'accountingbankserviceretryjob',
      'triggerrejectconductbettask',
      'collectnowfinalflowsubmission',
      'collectnowgeneratereceiptnotificationjob',
      'collectnowgeneratereceiptnotificationchjob',
      'collectnowgeneratereceiptnotificationrmjob',
      'primaryallocatecollection',
      'secondaryallocatecollection',
      'expirepastcollections',
      'createtaskfornewmficollections',
      'updateexpiredscheduledbatchstatus',
      'calculateusertatbatch',
      'cashdepositcutofftimeelapsedforcollectorjob',
      'createtaskbatch',
      'triggerrejectgroupbettask',
      'colltostagnphandofffilesyncjob',
      'triggerrejectindividualbettask',
      'childloaneventprocessingbatchjob',
      'loanrecurringpaymentbatchapi',
      'deleteaccountingtaskusingcode',
      'loanadvancerepayment',
      'deathforeclosureinsurancejob',
      'bulksgtodisbursementcancellationjob',
      'bulksgtopostdisbursementinsuranceupdatejob',
      'updateloanaccountderivedfieldsmonthlyjob',
      'generatenocfilejob',
      'proactiveexcessamountrefund',
      'proactiveexcessamountrefundstaging',
      'proactivereversetransaction',
      'generatetbzeroisationreport',
      'trialbalancezeroisationjob',
      'triggernetoffmarking',
      'loaninstallmentbouncenotificationjob',
      'loaninstallmentduenotificationjob',
      'apyregistration',
      'triggerckycapicallbatch',
      'generatecustomerleveldataextractjob',
      'triggerdisburseloan',
      'triggerdocumentdispatchtask',
      'ftsaccountopeningformbatch',
      'triggeruploaddocument',
      'runnefttransactionuploadjob',
      'notifyusersforpendingtasksjob',
      'generateperformancesummaryjob',
      'rejectexpiredgroupcasatask',
      'triggerrejectpdctask',
      'reminderforptpcalendercustomerjob',
      'reminderforptpcalenderuserjob',
      'reminderforptpcalenderuserjobrm',
      'assetbasefilesyncjob',
      'generateenachrepresentationfile',
      'processingsireversefeedfiles',
      'retrysijob',
      'supervisordashboardloancategorytaggingjob',
      'supervisordashboardskippedptptaggingjob',
      'supervisorreviewtaskjob',
      'colltostagnptrialhistorysyncjob',
      'generatetrendandreviewdashboardjob',
      'triggernotifications'
    )
  );

-- UPDATE force_msg_driven = 'TRUE' for all jobs
-- NOTE: Better than force_consumer_async for high-throughput scenarios (event-driven vs polling)
UPDATE batch_job_parameter 
SET param_value = 'TRUE' 
WHERE param_name = 'force_msg_driven' 
  AND job_id IN (
    SELECT id FROM batch_job 
    WHERE LOWER(TRIM(name)) IN (
      'loanaccountdpdcalcjob',
      'loanaccountassetcriteriasjob',
      'loanaccountassetclassificationjob',
      'penalinterestaccrualcalculation',
      'penalinterestaccrualbooking',
      'loanaccountclosure',
      'interestaccrualcalculation',
      'interestaccrualposting',
      'loanaccountbillingjob',
      'updateloanaccountderivedfieldsjob',
      'accountingbankserviceretryjob',
      'triggerrejectconductbettask',
      'collectnowfinalflowsubmission',
      'collectnowgeneratereceiptnotificationjob',
      'collectnowgeneratereceiptnotificationchjob',
      'collectnowgeneratereceiptnotificationrmjob',
      'primaryallocatecollection',
      'secondaryallocatecollection',
      'expirepastcollections',
      'createtaskfornewmficollections',
      'updateexpiredscheduledbatchstatus',
      'calculateusertatbatch',
      'cashdepositcutofftimeelapsedforcollectorjob',
      'createtaskbatch',
      'triggerrejectgroupbettask',
      'colltostagnphandofffilesyncjob',
      'triggerrejectindividualbettask',
      'childloaneventprocessingbatchjob',
      'loanrecurringpaymentbatchapi',
      'deleteaccountingtaskusingcode',
      'loanadvancerepayment',
      'deathforeclosureinsurancejob',
      'bulksgtodisbursementcancellationjob',
      'bulksgtopostdisbursementinsuranceupdatejob',
      'updateloanaccountderivedfieldsmonthlyjob',
      'generatenocfilejob',
      'proactiveexcessamountrefund',
      'proactiveexcessamountrefundstaging',
      'proactivereversetransaction',
      'generatetbzeroisationreport',
      'trialbalancezeroisationjob',
      'triggernetoffmarking',
      'loaninstallmentbouncenotificationjob',
      'loaninstallmentduenotificationjob',
      'apyregistration',
      'triggerckycapicallbatch',
      'generatecustomerleveldataextractjob',
      'triggerdisburseloan',
      'triggerdocumentdispatchtask',
      'ftsaccountopeningformbatch',
      'triggeruploaddocument',
      'runnefttransactionuploadjob',
      'notifyusersforpendingtasksjob',
      'generateperformancesummaryjob',
      'rejectexpiredgroupcasatask',
      'triggerrejectpdctask',
      'reminderforptpcalendercustomerjob',
      'reminderforptpcalenderuserjob',
      'reminderforptpcalenderuserjobrm',
      'assetbasefilesyncjob',
      'generateenachrepresentationfile',
      'processingsireversefeedfiles',
      'retrysijob',
      'supervisordashboardloancategorytaggingjob',
      'supervisordashboardskippedptptaggingjob',
      'supervisorreviewtaskjob',
      'colltostagnptrialhistorysyncjob',
      'generatetrendandreviewdashboardjob',
      'triggernotifications'
    )
  );

-- ============================================================================
-- SECTION 2: INSERT STATEMENTS
-- ============================================================================

-- INSERT force_chunk for original jobs (value: '100')
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_chunk',
    '100',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_chunk'
);

-- INSERT force_chunk for new jobs (value: '20')
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_chunk',
    '20',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_chunk'
);

-- INSERT force_grid_size for original jobs (value: '50')
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_grid_size',
    '50',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_grid_size'
);

-- INSERT force_grid_size for new jobs (value: '24')
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_grid_size',
    '24',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_grid_size'
);

-- INSERT force_async = 'TRUE' for all jobs
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_async',
    'TRUE',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob',
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_async'
);

-- INSERT is_multi_node = 'TRUE' for all jobs
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'is_multi_node',
    'TRUE',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob',
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'is_multi_node'
);

-- INSERT force_consumer_async = 'FALSE' for all jobs
-- NOTE: Using force_msg_driven instead (better for high-throughput scenarios)
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_consumer_async',
    'FALSE',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob',
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_consumer_async'
);

-- INSERT force_ex_channel = 'FALSE' for all jobs
-- NOTE: Set to 'TRUE' only if DB connection pool is large enough (100+ connections)
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_ex_channel',
    'FALSE',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob',
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_ex_channel'
);

-- INSERT force_task_executor = 'FALSE' for all jobs
-- NOTE: Set to 'TRUE' only if DB connection pool is very large (200+ connections)
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_task_executor',
    'FALSE',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob',
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_task_executor'
);

-- INSERT force_msg_driven = 'TRUE' for all jobs
-- NOTE: Better than force_consumer_async for high-throughput scenarios (event-driven vs polling)
INSERT INTO batch_job_parameter (job_id, param_name, param_value, param_type)
SELECT 
    bj.id,
    'force_msg_driven',
    'TRUE',
    'String'
FROM batch_job bj
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob',
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
AND NOT EXISTS (
    SELECT 1 FROM batch_job_parameter bjp 
    WHERE bjp.job_id = bj.id 
    AND bjp.param_name = 'force_msg_driven'
);

-- ============================================================================
-- VERIFICATION QUERY
-- ============================================================================
-- Check updated parameters for all jobs
SELECT 
    bj.id as job_id,
    bj.name as job_name,
    bjp.param_name,
    bjp.param_value
FROM batch_job bj
LEFT JOIN batch_job_parameter bjp ON bj.id = bjp.job_id 
    AND bjp.param_name IN (
        'force_chunk', 
        'force_grid_size', 
        'force_async', 
        'is_multi_node',
        'force_consumer_async',
        'force_ex_channel',
        'force_task_executor',
        'force_msg_driven'
    )
WHERE LOWER(TRIM(bj.name)) IN (
    'loanaccountdpdcalcjob',
    'loanaccountassetcriteriasjob',
    'loanaccountassetclassificationjob',
    'penalinterestaccrualcalculation',
    'penalinterestaccrualbooking',
    'loanaccountclosure',
    'interestaccrualcalculation',
    'interestaccrualposting',
    'loanaccountbillingjob',
    'updateloanaccountderivedfieldsjob',
    'accountingbankserviceretryjob',
    'triggerrejectconductbettask',
    'collectnowfinalflowsubmission',
    'collectnowgeneratereceiptnotificationjob',
    'collectnowgeneratereceiptnotificationchjob',
    'collectnowgeneratereceiptnotificationrmjob',
    'primaryallocatecollection',
    'secondaryallocatecollection',
    'expirepastcollections',
    'createtaskfornewmficollections',
    'updateexpiredscheduledbatchstatus',
    'calculateusertatbatch',
    'cashdepositcutofftimeelapsedforcollectorjob',
    'createtaskbatch',
    'triggerrejectgroupbettask',
    'colltostagnphandofffilesyncjob',
    'triggerrejectindividualbettask',
    'childloaneventprocessingbatchjob',
    'loanrecurringpaymentbatchapi',
    'deleteaccountingtaskusingcode',
    'loanadvancerepayment',
    'deathforeclosureinsurancejob',
    'bulksgtodisbursementcancellationjob',
    'bulksgtopostdisbursementinsuranceupdatejob',
    'updateloanaccountderivedfieldsmonthlyjob',
    'generatenocfilejob',
    'proactiveexcessamountrefund',
    'proactiveexcessamountrefundstaging',
    'proactivereversetransaction',
    'generatetbzeroisationreport',
    'trialbalancezeroisationjob',
    'triggernetoffmarking',
    'loaninstallmentbouncenotificationjob',
    'loaninstallmentduenotificationjob',
    'apyregistration',
    'triggerckycapicallbatch',
    'generatecustomerleveldataextractjob',
    'triggerdisburseloan',
    'triggerdocumentdispatchtask',
    'ftsaccountopeningformbatch',
    'triggeruploaddocument',
    'runnefttransactionuploadjob',
    'notifyusersforpendingtasksjob',
    'generateperformancesummaryjob',
    'rejectexpiredgroupcasatask',
    'triggerrejectpdctask',
    'reminderforptpcalendercustomerjob',
    'reminderforptpcalenderuserjob',
    'reminderforptpcalenderuserjobrm',
    'assetbasefilesyncjob',
    'generateenachrepresentationfile',
    'processingsireversefeedfiles',
    'retrysijob',
    'supervisordashboardloancategorytaggingjob',
    'supervisordashboardskippedptptaggingjob',
    'supervisorreviewtaskjob',
    'colltostagnptrialhistorysyncjob',
    'generatetrendandreviewdashboardjob',
    'triggernotifications'
)
ORDER BY bj.name, bjp.param_name;
