#!/usr/bin/env python3
"""
Contract graph — scan orchestration XML + MessageBroker across all microservices.
Exports contracts.jsonl, syncs FTG, links precedents from changelog.

  contract_graph.py scan [--json]
  contract_graph.py stats
  contract_graph.py list [--money] [--protocol HTTP_INTERNAL|KAFKA]
  contract_graph.py show <contract-id>
  contract_graph.py gaps          # money contracts without FTG / tests
  contract_graph.py sync-ftg      # auto-link FTG ids + suggest new rows
  contract_graph.py precedents    # changelog → contract mapping
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[2]
KG_BIN = WORKSPACE / "cursor-bundle/kg/bin"
sys.path.insert(0, str(KG_BIN))

from _contract_scan import iter_all_contracts, scan_stats, scan_workspace  # noqa: E402

CONTRACTS = WORKSPACE / "cursor-bundle/flow-test/contracts.jsonl"
FLOWS = WORKSPACE / "cursor-bundle/flow-test/flows.jsonl"
CHANGELOG = WORKSPACE / "cursor-bundle/brain/changelog/CHANGELOG.md"
CURSOR_CL = WORKSPACE / ".cursor/changelog.md"
REGISTRY = WORKSPACE / "scripts/testing/registry.json"

# consumer request → FTG id (hand-curated spine)
REQUEST_TO_FTG: dict[str, str] = {
    "disburseLoan": "ftf:disburse.http",
    "loanRepayment": "ftf:repayment.standard",
    "loanPrepayment": "ftf:foreclosure.initiate_novopay",
    "updateCollectionBatchDetails": "ftf:foreclosure.batch_expiry_lms",
    "collectionLoanRepayment": "ftf:repayment.standard",
    "loanAccountPartPrepayment": "ftf:partprepayment.approve",
    "loanDisbursementCancellation": "ftf:disb_cancellation.initiate",
    "loanAccountTransactionReversal": "ftf:reversal.txn",
    "dpiAccrualCalculation": "ftf:dpi.eod_chain",
    "dpiAccrualBooking": "ftf:dpi.eod_chain",
    "dpiBilling": "ftf:dpi.eod_chain",
    "loanAccountDpdCalcJob": "ftf:batch.dpd_calc",
    "glBalanceZeroisation": "ftf:gl.zeroisation",
    "fetchLoanForeclosureSimulationDetails": "ftf:foreclosure.simulation",
    "getLoanAccountOverviewDetails": "ftf:dpi.read_apis",
    "getLoanAccountBasicDetails": "ftf:health.loan_read",
    "interestAccrualPosting": "ftf:interest.normal_accrual",
    "penalInterestAccrualBooking": "ftf:interest.penal_accrual",
    "loanWriteoff": "ftf:writeoff.status",
    "postTransaction": "ftf:repayment.standard",
    "cancelCollections": "ftf:foreclosure.complete",
    "bulkCollectionData": "ftf:collections.bulk_kafka",
    "bulkCollectionFailedRecord": "ftf:collections.bulk_failed_kafka",
    "createOrUpdateLoanAccount": "ftf:onboarding.create_loan_account",
    "deathForeclosureInsuranceJob": "ftf:death_foreclosure.insurance_batch",
    "updateTaskWorkflow": "ftf:task.workflow",
    "deleteTask": "ftf:task.workflow",
    "loanAccountBillingJob": "ftf:batch.billing",
}


def load_jsonl(path: Path) -> list[dict]:
    rows = []
    if not path.is_file():
        return rows
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            rows.append(json.loads(line))
    return rows


def save_contracts(rows: list[dict]) -> None:
    lines = ["# Cross-service contracts — auto-generated by contract_graph.py scan"]
    for row in rows:
        lines.append(json.dumps(row, separators=(",", ":")))
    CONTRACTS.write_text("\n".join(lines) + "\n", encoding="utf-8")


def load_flows_by_id() -> dict[str, dict]:
    return {r["id"]: r for r in load_jsonl(FLOWS)}


def load_flows_by_request() -> dict[str, list[dict]]:
    by_req: dict[str, list[dict]] = defaultdict(list)
    for r in load_jsonl(FLOWS):
        by_req[r.get("request", "")].append(r)
    return by_req


def parse_precedents() -> dict[str, list[str]]:
    """Map api/request tokens → JIRA / SDCP ids from changelogs."""
    prec: dict[str, set[str]] = defaultdict(set)
    for path in (CHANGELOG, CURSOR_CL):
        if not path.is_file():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            tickets = re.findall(r"SDCP-\d+|GAP-\d+", line, re.I)
            if not tickets:
                continue
            low = line.lower()
            for token in REQUEST_TO_FTG:
                if token.lower() in low:
                    prec[token].update(tickets)
            for m in re.findall(r"apiName\s+(\w+)", line):
                prec[m].update(tickets)
    return {k: sorted(v) for k, v in prec.items()}


def link_ftg(contract: dict, flows_by_req: dict[str, list[dict]]) -> str | None:
    tests = contract.get("tests") or {}
    if tests.get("ftg_id"):
        return tests["ftg_id"]
    cons = contract.get("consumer") or {}
    req = cons.get("request") or cons.get("api")
    if req and req in REQUEST_TO_FTG:
        return REQUEST_TO_FTG[req]
    if req and flows_by_req.get(req):
        return flows_by_req[req][0]["id"]
    prod = contract.get("producer") or {}
    preq = prod.get("request")
    if preq and flows_by_req.get(preq):
        return flows_by_req[preq][0]["id"]
    return None


def coverage_for_ftg(ftg_id: str | None, flows: dict[str, dict]) -> str:
    if not ftg_id or ftg_id not in flows:
        return "gap"
    return flows[ftg_id].get("coverage", "gap")


def cmd_scan(args: argparse.Namespace) -> int:
    result = scan_workspace(WORKSPACE)
    rows = list(iter_all_contracts(result))
    precedents = parse_precedents()
    flows_by_req = load_flows_by_request()
    flows_by_id = load_flows_by_id()

    for c in rows:
        cons_req = (c.get("consumer") or {}).get("request")
        prod_req = (c.get("producer") or {}).get("request")
        for req in (cons_req, prod_req):
            if req and req in precedents:
                c.setdefault("precedents", [])
                for t in precedents[req]:
                    if t not in c["precedents"]:
                        c["precedents"].append(t)
        ftg = link_ftg(c, flows_by_req)
        c["tests"] = {
            "ftg_id": ftg,
            "coverage": coverage_for_ftg(ftg, flows_by_id),
        }

    save_contracts(rows)
    stats = scan_stats(result)
    stats["contracts_written"] = len(rows)
    stats["money_contracts"] = sum(1 for c in rows if c.get("money"))
    if args.json:
        print(json.dumps(stats, indent=2))
    else:
        print("Contract scan complete:")
        for k, v in stats.items():
            print(f"  {k}: {v}")
        print(f"  written: {CONTRACTS.relative_to(WORKSPACE)}")
    return 0


def cmd_stats(_: argparse.Namespace) -> int:
    rows = load_jsonl(CONTRACTS)
    if not rows:
        print("No contracts.jsonl — run: contract_graph.py scan")
        return 1
    money = [r for r in rows if r.get("money")]
    by_proto = defaultdict(int)
    for r in rows:
        by_proto[r.get("protocol", "?")] += 1
    print(f"contracts: {len(rows)}  money: {len(money)}")
    for p, n in sorted(by_proto.items()):
        print(f"  {p}: {n}")
    with_ftg = sum(1 for r in money if (r.get("tests") or {}).get("ftg_id"))
    print(f"  money with FTG link: {with_ftg}/{len(money)}")
    return 0


def cmd_list(args: argparse.Namespace) -> int:
    rows = load_jsonl(CONTRACTS)
    if args.money:
        rows = [r for r in rows if r.get("money")]
    if args.protocol:
        rows = [r for r in rows if r.get("protocol") == args.protocol]
    for r in rows:
        ftg = (r.get("tests") or {}).get("ftg_id") or "-"
        cov = (r.get("tests") or {}).get("coverage") or "gap"
        prod = r.get("producer", {})
        cons = r.get("consumer", {})
        left = prod.get("request") or prod.get("topic_prefix", "?")
        right = cons.get("request") or cons.get("bean", "?")
        print(f"{r['id'][:70]:70} {r.get('protocol','?'):14} {cov:8} {ftg}")
        print(f"    {prod.get('service','?')}:{left} → {cons.get('service','?')}:{right}")
    return 0


def cmd_show(cid: str) -> int:
    for r in load_jsonl(CONTRACTS):
        if r.get("id") == cid or cid in r.get("id", ""):
            print(json.dumps(r, indent=2))
            return 0
    print(f"Not found: {cid}", file=sys.stderr)
    return 1


def cmd_gaps() -> int:
    rows = [r for r in load_jsonl(CONTRACTS) if r.get("money")]
    print("Money contracts without FTG or with coverage=gap:\n")
    n = 0
    for r in rows:
        tests = r.get("tests") or {}
        ftg = tests.get("ftg_id")
        cov = tests.get("coverage", "gap")
        if not ftg or cov == "gap":
            n += 1
            print(f"  {r['id']}")
            print(f"    FTG={ftg or 'MISSING'} coverage={cov} precedents={r.get('precedents', [])}")
    if n == 0:
        print("  (none)")
    return 0


def cmd_sync_ftg(_: argparse.Namespace) -> int:
    """Suggest new FTG rows for money contracts missing FTG."""
    rows = load_jsonl(CONTRACTS)
    existing_requests = {r.get("request") for r in load_jsonl(FLOWS)}
    suggestions: list[str] = []

    for c in rows:
        if not c.get("money"):
            continue
        tests = c.get("tests") or {}
        if tests.get("ftg_id"):
            continue
        cons = c.get("consumer") or {}
        req = cons.get("request")
        if not req or req in existing_requests:
            continue
        suggestions.append(
            f"  NEW FTG for request={req}  contract={c['id'][:60]}…"
        )

    print("FTG sync suggestions (money contracts without FTG row):\n")
    if suggestions:
        for s in suggestions[:30]:
            print(s)
    else:
        print("  All money contracts linked to an FTG row (or consumer request already in flows.jsonl).")
    print("\nRun `contract_graph.py scan` after KG/FTG updates to refresh links.")
    return 0


def cmd_precedents(_: argparse.Namespace) -> int:
    prec = parse_precedents()
    rows = load_jsonl(CONTRACTS)
    print("Precedents linked to contracts:\n")
    shown = 0
    for c in rows:
        if not c.get("precedents"):
            continue
        shown += 1
        print(f"  {c['id'][:65]}")
        print(f"    {c['precedents']}")
    if shown == 0:
        print("  (run scan first to attach precedents from changelog)")
    print(f"\nChangelog index ({len(prec)} request tokens with tickets):")
    for req, tickets in sorted(prec.items())[:25]:
        print(f"  {req}: {', '.join(tickets)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Cross-service contract graph")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_scan = sub.add_parser("scan", help="Scan all repos → contracts.jsonl")
    p_scan.add_argument("--json", action="store_true")

    sub.add_parser("stats", help="Summary of contracts.jsonl")
    p_list = sub.add_parser("list", help="List contracts")
    p_list.add_argument("--money", action="store_true")
    p_list.add_argument("--protocol", choices=["HTTP_INTERNAL", "KAFKA"])
    p_show = sub.add_parser("show", help="Show one contract")
    p_show.add_argument("id")
    sub.add_parser("gaps", help="Money contracts missing proof")
    sub.add_parser("sync-ftg", help="FTG linkage suggestions")
    sub.add_parser("precedents", help="Show fix precedents on contracts")

    args = parser.parse_args()
    if args.cmd == "scan":
        return cmd_scan(args)
    if args.cmd == "stats":
        return cmd_stats(args)
    if args.cmd == "list":
        return cmd_list(args)
    if args.cmd == "show":
        return cmd_show(args.id)
    if args.cmd == "gaps":
        return cmd_gaps()
    if args.cmd == "sync-ftg":
        return cmd_sync_ftg(args)
    if args.cmd == "precedents":
        return cmd_precedents(args)
    return 1


if __name__ == "__main__":
    sys.exit(main())
